image: python:3.5
git:
  path: github.com/swadhar/pythonrepo1
script:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
clone:
  path: github.com/swadhar/pythonrepo1
build:
  image: python:3.5
  commands:
    - echo "build commands"
    - echo "no build command"
    - echo "no test command"
publish:
  docker:
    file: ./Dockerfile
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
